version: "3"
services:
    app:
        image: lv_dev
        hostname: ${APP_HOSTNAME:-lv}
        build:
            context: .
            target: development
            args:
                WWWGROUP: "${WWWGROUP}"
        ports:
            - ${APP_PORT:-80}:80
            - ${VITE_DS_PORT:-3000}:${VITE_DS_PORT:-3000}
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
        volumes:
            - ./:/var/www/html
            - ${NPM_CACHE:-/var/www/html/npm/cache}:/root/.npm

    redis:
        image: 'redis:alpine'
        ports:
        - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
        - 'lvredis:/data'
        networks:
        - sail
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']

volumes:
  lvmysql:
    driver: local
  lvredis:
    driver: local
